name: ci-test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: simple-bank
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v2

    - name: RUn migrations
      run: make migrateup

    - name: Test
      run: go test -v -cover ./...
